from .lerico_resolution_forge import NODE_CLASS_MAPPINGS as V1_NODE_CLASS_MAPPINGS
from .lerico_resolution_forge import NODE_DISPLAY_NAME_MAPPINGS as V1_NODE_DISPLAY_NAME_MAPPINGS
from .lerico_resolution_forge_v2 import NODE_CLASS_MAPPINGS as V2_NODE_CLASS_MAPPINGS
from .lerico_resolution_forge_v2 import NODE_DISPLAY_NAME_MAPPINGS as V2_NODE_DISPLAY_NAME_MAPPINGS

WEB_DIRECTORY = "./js"

NODE_CLASS_MAPPINGS = {
    **V1_NODE_CLASS_MAPPINGS,
    **V2_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **V1_NODE_DISPLAY_NAME_MAPPINGS,
    **V2_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
